spring:
  datasource:
    url: jdbc:mysql://localhost/github?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: MuseU2&Coldplay

  jpa:
    hibernate:
      ddl-auto: update

  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

  server:
    port: 8080
  security:
    basic:
      enabled: false

  storage:
    url: "storage"
    image:
      url: "/image"